Adding new attributes to our Pizza card
mahnoorjanjua505/FoodCoupon-with-HTML-CSS pull request #1
Opened 2023-09-24 18:01 UTC by munzah-shah

This PR does the following:

- [x] Updates the title of the page
- [ ] Updates the attributes of Pizza

2023-09-24 18:15 UTC, munzah-shah commented on index.html
> +    <title>Food Coupon page | HTML and CSS</title>
add "by Mahnoor" again

2023-09-24 18:16 UTC, munzah-shah commented on index.html
> +    <title>Food Coupon page | HTML and CSS</title>
no I don't want to

2023-09-24 18:19 UTC, munzah-shah reviewed
Sugggestion: revert back all changes.

2023-09-25 16:21 UTC, mahnoorjanjua505 requested changes
reverse the changes!

2023-09-26 17:51 UTC, merged